openapi: 3.0.3
info:
  title: Hub API
  description: APIs for dashboard
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1

tags:
  - name: Dashboard
  - name: Transmission
  - name: Configuration

paths:
  /transmit-data:
    post:
      tags:
        - Transmission
      summary: transmit data to the server
      operationId: transmitData
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TransmitDataRequest"
      responses:
        "201":
          description: Successful response
  /export-data:
    get:
      tags:
        - Dashboard
      summary: Export data within a date range
      operationId: exportData
      parameters:
        - $ref: "#/components/parameters/dateFrom"
        - $ref: "#/components/parameters/dateTo"
      responses:
        "200":
          description: CSV file containing the requested metrics
          content:
            text/csv:
              schema:
                type: string
                format: binary
  /system-configuration:
    get:
      tags:
        - Configuration
      summary: Get system configuration
      operationId: getSystemConfiguration
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SystemConfiguration"
  /containers/{containerId}/pack-metrics:
    get:
      tags:
        - Dashboard
      operationId: getContainerPackMetrics
      summary: get the metrics of all packs in a container
      parameters:
        - $ref: "#/components/parameters/containerId"
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ContainerPackMetricsResponse"
  /containers/{containerId}/pack-metrics/{packId}:
    get:
      tags:
        - Dashboard
      summary: Get the metrics of a pack
      operationId: getPackMetrics
      parameters:
        - $ref: "#/components/parameters/containerId"
        - $ref: "#/components/parameters/packId"
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PackMetricsResponse"
  /containers/{containerId}/packs/{packId}/cells-metrics/{cellId}:
    get:
      tags:
        - Dashboard
      summary: Get the metrics of a cell
      operationId: getCellMetrics
      parameters:
        - $ref: "#/components/parameters/containerId"
        - $ref: "#/components/parameters/packId"
        - $ref: "#/components/parameters/cellId"
        - $ref: "#/components/parameters/dateFrom"
        - $ref: "#/components/parameters/dateTo"
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CellMetricsResponse"
  /overview:
    get:
      tags:
        - Dashboard
      summary: Get dashboard overview
      operationId: getDashboardOverview
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Overview"
components:
  schemas:
    EisMeasurement:
      type: object
      properties:
        containerId:
          type: string
        clusterId:
          type: string
        packId:
          type: string
        cellId:
          type: string
        realImpedance:
          type: number
          format: double
        frequency:
          type: number
          format: double
        imaginaryImpedance:
          type: number
          format: double
        voltage:
          type: number
          format: double
        creationTime:
          type: string
          format: date-time
        temperature:
          type: number
          format: double
    TransmitDataRequest:
      type: object
      properties:
        eisMeasurements:
          type: array
          items:
            $ref: "#/components/schemas/EisMeasurement"
        cellStatistics:
          type: array
          items:
            $ref: "#/components/schemas/CellStatistics"
        packStatistics:
          type: array
          items:
            $ref: "#/components/schemas/PackStatistics"
    PackMetricsResponse:
      type: object
      properties:
        packHistogram:
          $ref: "#/components/schemas/PackHistogram"
        metrics:
          $ref: "#/components/schemas/PackMetrics"
        suggestion:
          type: string
        characteristicFrequencies:
          $ref: "#/components/schemas/CharacteristicFrequencies"
        cellColors:
          type: array
          items:
            $ref: "#/components/schemas/CellColorInfo"
    CharacteristicFrequencies:
      type: object
      properties:
        impedance10Hz:
          type: number
          format: double
        impedance10000Hz:
          type: number
          format: double
    Cluster:
      type: object
      properties:
        id:
          type: string
        packs:
          type: array
          items:
            type: string
    Container:
      type: object
      properties:
        id:
          type: string
        clusters:
          type: array
          items:
            $ref: "#/components/schemas/Cluster"
    SystemConfiguration:
      type: object
      properties:
        containers:
          type: array
          items:
            $ref: "#/components/schemas/Container"
        packType:
          type: string
          enum: ["pack52", "pack104"]
    Overview:
      type: object
      properties:
        monthlyInspections:
          type: integer
        totalInspections:
          type: integer
          format: int64
        totalMeasurements:
          type: integer
          format: int64
        totalRiskySamples:
          type: integer
        cumulativeRiskIdentifications:
          type: integer
        lastUpdatedAt:
          type: string
          format: date-time
        alertTexts:
          type: array
          items:
            type: string
    PackStatistics:
      type: object
      properties:
        containerId:
          type: string
        clusterId:
          type: string
        packId:
          type: string
        realTimeId:
          type: string
        maxAbsImpedance:
          type: number
          format: double
        minAbsImpedance:
          type: number
          format: double
        maxCoefficientOfVariation:
          type: number
          format: double
        minCoefficientOfVariation:
          type: number
          format: double
        maxImpedanceStdDev:
          type: number
          format: double
        minImpedanceStdDev:
          type: number
          format: double
        temperature:
          type: number
          format: double
        absImpedanceMean:
          type: number
          format: double
        impedanceStdDev:
          type: number
          format: double
        coefficientOfVariation:
          type: number
          format: double
        dispersion:
          type: number
          format: double
        degradationLevel:
          $ref: "#/components/schemas/DegradationLevel"
        suggestion:
          type: string
        alertText:
          type: string
        characteristicFrequencies:
          $ref: "#/components/schemas/CharacteristicFrequencies"
        creationTime:
          type: string
          format: date-time
        cellColors:
          type: object
          description: JSON representation of cell color information
    PackMetrics:
      type: object
      properties:
        absImpedanceMean:
          type: number
          format: double
        impedanceStdDev:
          type: number
          format: double
        coefficientOfVariation:
          type: number
          format: double
        dispersion:
          type: number
          format: double
        degradationLevel:
          $ref: "#/components/schemas/DegradationLevel"
    PackHistogram:
      type: array
      items:
        $ref: "#/components/schemas/PackHistogramPoint"
    PackHistogramPoint:
      type: object
      properties:
        absImpedanceMean:
          type: number
          format: double
        maxAbsImpedance:
          type: number
          format: double
        minAbsImpedance:
          type: number
          format: double
        impedanceStdDev:
          type: number
          format: double
    ClusterPackHistogram:
      type: object
      properties:
        packId:
          type: string
        packHistogram:
          type: array
          items:
            $ref: "#/components/schemas/PackHistogramPoint"
    ClusterHistogram:
      type: array
      items:
        $ref: "#/components/schemas/ClusterPackHistogram"
    CellHistogram:
      type: array
      items:
        $ref: "#/components/schemas/CellHistogramPoint"
    CellHistogramPoint:
      type: object
      properties:
        realPart10Hz:
          type: number
          format: double
        imagPart10Hz:
          type: number
          format: double
        r0:
          type: number
          format: double
        timestamp:
          type: string
          format: date-time
    CellMetricsResponse:
      type: object
      properties:
        histogram:
          $ref: "#/components/schemas/CellHistogram"
        nyquistPlot:
          $ref: "#/components/schemas/NyquistPlot"
        bodePlot:
          $ref: "#/components/schemas/BodePlot"
        drtPlot:
          $ref: "#/components/schemas/DrtPlot"
        realPartCorrelation:
          $ref: "#/components/schemas/Matrix"
        imagPartCorrelation:
          $ref: "#/components/schemas/Matrix"
        metrics:
          $ref: "#/components/schemas/CellMetrics"
        equivalentCircuitDiagram:
          $ref: "#/components/schemas/EquivalentCircuitDiagram"
    EquivalentCircuitDiagram:
      type: object
      properties:
        r0:
          type: number
          format: double
        rct:
          type: number
          format: double
        cdl:
          type: number
          format: double
        zw:
          type: number
          format: double
    Range:
      type: object
      properties:
        max:
          type: number
          format: double
        min:
          type: number
          format: double
    NyquistPlot:
      type: object
      properties:
        metrics:
          type: array
          items:
            $ref: "#/components/schemas/NyquistPlotPoint"
        heatMap:
          $ref: "#/components/schemas/Matrix"
        xAxisRange:
          $ref: "#/components/schemas/Range"
        yAxisRange:
          $ref: "#/components/schemas/Range"
    NyquistPlotPoint:
      type: object
      properties:
        realImpedance:
          type: number
          format: double
        imaginaryImpedance:
          type: number
          format: double
    BodePlot:
      type: array
      items:
        $ref: "#/components/schemas/BodePlotPoint"
    BodePlotPoint:
      type: object
      properties:
        frequency:
          type: number
          format: double
        phase:
          type: number
          format: double
        amplitude:
          type: number
          format: double
    DrtPlot:
      type: array
      items:
        $ref: "#/components/schemas/DrtPlotPoint"
    DrtPlotPoint:
      type: object
      properties:
        relaxT:
          type: number
          format: double
        yT:
          type: number
          format: double
    Matrix:
      type: array
      items:
        type: array
        items:
          type: number
          format: double
    CellStatistics:
      type: object
      properties:
        containerId:
          type: string
        clusterId:
          type: string
        packId:
          type: string
        groupId:
          type: string
        cellId:
          type: string
        realTimeId:
          type: string
        absImpedanceMean:
          type: number
          format: double
        impedanceStdDev:
          type: number
          format: double
        coefficientOfVariation:
          type: number
          format: double
        phase:
          type: number
          format: double
        impedanceMeanToMaxRatio:
          type: number
          format: double
        impedanceMeanToMinRatio:
          type: number
          format: double
        impedanceMeanToAvgRatio:
          type: number
          format: double
        impedanceStdDevToMaxRatio:
          type: number
          format: double
        impedanceStdDevToMinRatio:
          type: number
          format: double
        impedanceStdDevToAvgRatio:
          type: number
          format: double
        bodePlot:
          $ref: "#/components/schemas/BodePlot"
        nyquistPlot:
          $ref: "#/components/schemas/NyquistPlot"
        drtPlot:
          $ref: "#/components/schemas/DrtPlotPoint"
        realPartCorrelation:
          $ref: "#/components/schemas/Matrix"
        imagPartCorrelation:
          $ref: "#/components/schemas/Matrix"
        equivalentCircuitDiagram:
          $ref: "#/components/schemas/EquivalentCircuitDiagram"
        creationTime:
          type: string
          format: date-time
        realPart10Hz:
          type: number
          format: double
        imaginaryPart10Hz:
          type: number
          format: double
        maxImpedanceStdDev:
          type: number
          format: double
        minImpedanceStdDev:
          type: number
          format: double
        maxAbsImpedance:
          type: number
          format: double
        minAbsImpedance:
          type: number
          format: double
        maxCoefficientOfVariation:
          type: number
          format: double
        minCoefficientOfVariation:
          type: number
          format: double
    CellMetrics:
      type: object
      properties:
        maxImpedanceStdDev:
          type: number
          format: double
        minImpedanceStdDev:
          type: number
          format: double
        maxAbsImpedance:
          type: number
          format: double
        minAbsImpedance:
          type: number
          format: double
        maxCoefficientOfVariation:
          type: number
          format: double
        minCoefficientOfVariation:
          type: number
          format: double
        absImpedanceMean:
          type: number
          format: double
        impedanceStdDev:
          type: number
          format: double
        coefficientOfVariation:
          type: number
          format: double
        impedanceMeanToMaxRatio:
          type: number
          format: double
        impedanceMeanToMinRatio:
          type: number
          format: double
        impedanceMeanToAvgRatio:
          type: number
          format: double
        impedanceStdDevToMaxRatio:
          type: number
          format: double
        impedanceStdDevToMinRatio:
          type: number
          format: double
        impedanceStdDevToAvgRatio:
          type: number
          format: double
    ContainerPackMetricsResponse:
      type: object
      properties:
        packHistograms:
          $ref: "#/components/schemas/ClusterHistogram"
    CellColorInfo:
      type: object
      properties:
        cellId:
          type: string
        color:
          type: string
    DegradationLevel:
      type: string
      enum: ["Normal", "Mild", "Severe"]
  parameters:
    containerId:
      in: path
      required: true
      name: containerId
      schema:
        type: string
    packId:
      in: path
      required: true
      name: packId
      schema:
        type: string
    cellId:
      in: path
      required: true
      name: cellId
      schema:
        type: string
    clusterId:
      in: path
      schema:
        type: string
      required: true
      name: clusterId
    dateFrom:
      in: query
      schema:
        type: string
        format: date-time
      required: false
      name: dateFrom
    dateTo:
      in: query
      schema:
        type: string
        format: date-time
      required: false
      name: dateTo
